#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage()
{
    cat <<EOF
Usage: yamcha-config [OPTIONS]

Options:
  [--prefix[=DIR]]
  [--exec-prefix[=DIR]]
  [--libs]
  [--cflags]
  [--modeldir]
  [--sharedir]
  [--libexecdir]
  [--help]
  [--version]
EOF

    exit $1
}

if test $# -eq 0; then
    usage 1
fi

cflags=false
libs=false

while test $# -gt 0; do
    case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
    esac

    case "$1" in
    --prefix=*)
	prefix=$optarg
        if test $exec_prefix_set = no ; then
          exec_prefix=$optarg
        fi
	;;

    --prefix)
	echo $prefix
	;;

    --exec-prefix=*)
	exec_prefix=$optarg
	exec_prefix_set=yes
	;;

    --exec-prefix)
	echo $exec_prefix
	;;

    --version)
	echo 0.33
	exit 0
	;;

    --help)
	usage 0
	;;

    --cflags)
        if test ${prefix}/include != /usr/include ; then
          includes=-I${prefix}/include
        fi
        echo $includes
       	;;

    --libs)
       	echo -L${exec_prefix}/lib -lyamcha  -lm -lstdc++
       	;;

    --modeldir)
       	echo /usr/local/lib/yamcha/model
       	;;

    --libexecdir)
       	echo /usr/local/libexec/yamcha
       	;;

    *)
	usage
	exit 1
	;;
    esac
    shift
done

exit 0
